drop table if exists memberRepository CASCADE;
create table memberRepository
(
    manageSeq bigint generated by default as identity,
    loginId varchar(10),
    password varchar(10),
    name varchar(10),
    nickName varchar(10),
    primary key (manageSeq)
);

drop table if exists meessageRepository CASCADE;
create table messageRepository
(
    manageSeq bigint generated by default as identity,
    sender varchar(10),
    recipient varchar(10),
    date varchar(11),
    title varchar(10),
    message varchar(10),
    isRead varchar(10),
    primary key (manageSeq)
);

drop table if exists noteRepository CASCADE;
create table noteRepository
(
    manageSeq bigint generated by default as identity,
    nickName varchar(10),
    date varchar(11),
    title varchar(10),
    content varchar(10),
    userUUID varchar(36),
    roomUUID varchar(36),
    primary key (manageSeq)
);